### ISSUE TITLE
Frequent re-compiling

### ISSUE THREAD

**Issue by vera** [nsg-ethz/p4-utils#15]
I have noticed the following issues when using `p4run`:

1. The P4 program is re-compiled every time `p4run` is executed, even when the file has not changed.
2. When executing `p4switch_reboot` in the mininet console, the P4 program is always re-compiled on the first reboot, even when the file has not changed. On all following reboots, it is correctly not re-compiled.

I saw that you do attempt to limit re-compiling by checking if the files have been modified: https://github.com/nsg-ethz/p4-utils/blob/master/p4utils/mininetlib/cli.py#L128
However, this apparently only kicks in after the first re-compiling.

I think it would make `p4run` faster and more convenient to use if this could be improved.

**Comment by edgar-costa** [comment]
Hi Vera,

Yes you are right, this happens because when the program starts it does not have any "time" reference. I could maybe check the last modification of the `.p4` and `.json` files. In theory that should work, unless I am missing something now.
