### ISSUE TITLE
Send packet from controller and set egress port to controller

### ISSUE THREAD

**Issue by NofelYaseen** [nsg-ethz/p4-utils#16]
Is there a network interface between the controller and the switch to send and receive packets?

I can potentially send the packet by sending packet to one of the switch interfaces, for example: s1-eth1.

But is there a way set egress_port to <controller_port> such that I receive the packet at the controller?

**Comment by machadoatz** [comment]
I think you have to use the clone or clone3 function in order to do that.

Don't know what you are working with but, assuming you are working with p4-learning from nsg-ethz you can find some documentation for the clone function in [v1model.p4 - clone3](https://github.com/p4lang/p4c/blob/7749dfbf2edc0450898b5537feb32abb970f5407/p4include/v1model.p4#L633).

I believe this will also be useful:
- [simple-switch doc](https://github.com/nsg-ethz/p4-learning/blob/master/documentation/simple-switch.md#standard-metadata-1) - read ```clone_spec```
- [example from p4utils p4-learning](https://github.com/nsg-ethz/p4-learning/tree/master/examples/copy_to_cpu)

**Comment by edgar-costa** [comment]
Sorry for the late response.

As @machadoatz says, you have to use the clone or clone3 when you want to send packets to the controller by using another packet as a trigger. However, if you want to use a packet itself, meaning that it does not need to be forwarded, you can simply set the output port as the controller port.

However, I believe this was not what you were asking. You were asking how to even create a "cpu port", right? If you are using p4-utils, in the json configuration file you can enable a cpu port, that will add an "extra" port to the bmv2 switch that will be accessible from the main namespace, you can then listen to that port and send packets to it.

The best example where this is done is in the [l2-learning exercise from p4-learning](https://github.com/nsg-ethz/p4-learning/tree/master/exercises/04-L2_Learning)

**Comment by NofelYaseen** [comment]
Thank you for your responses.
Sorry, I didn't close the issue earlier. 
This is what I ended up doing.

In `p4app.json`, I added a control_port like this:

```
{
...
    "topology" : {
         ...
         "s1": {
         "cli_input": "s1-commands.txt",
         "program": "forwarding.p4",
         "control_port" : 31
        },
       ...
    }
}
```

Passed the control_port value to `class P4Switch(Switch)` constructor, and in `def start(self, controllers = None)` function, added following lines to bring port up:
```
def start(self, controllers = None):
...
    if self.control_port is not None:
            get_cp_intf_up(self.name+"-ethd", self.name+"-ethc")
            args.extend(['-i', str(self.control_port) + "@" + self.name + "-ethd"])
...
```

In `def stop(self)`, added the following line to bring down port:
```
def stop(self):
    ...
    get_cp_intf_down(self.name+"-ethd", self.name+"-ethc")
```

The functions `get_cp_intf_down` and `get_cp_intf_up` are in `p4utils/utils/utils.py` file:

```
def get_cp_intf_up(dp_intf, cp_intf):
    bashCommand = "sudo ip link delete " + dp_intf + " > /dev/null 2>&1 || true"
    process = subprocess.Popen(bashCommand, stdout=subprocess.PIPE, shell=True)
    output, error = process.communicate()

    bashCommand = "sudo ip link delete " + cp_intf + " > /dev/null 2>&1 || true"
    process = subprocess.Popen(bashCommand, stdout=subprocess.PIPE, shell=True)
    output, error = process.communicate()

    bashCommand = "sudo ip link add " + dp_intf + " type veth peer name " + cp_intf
    process = subprocess.Popen(bashCommand, stdout=subprocess.PIPE, shell=True)
    output, error = process.communicate()

    bashCommand = "sudo sysctl -q net.ipv6.conf." + dp_intf + ".disable_ipv6=1"
    process = subprocess.Popen(bashCommand, stdout=subprocess.PIPE, shell=True)
    output, error = process.communicate()

    bashCommand = "sudo sysctl -q net.ipv6.conf." + cp_intf + ".disable_ipv6=1"
    process = subprocess.Popen(bashCommand, stdout=subprocess.PIPE, shell=True)
    output, error = process.communicate()

    bashCommand = "sudo ifconfig " + dp_intf + " up promisc"
    process = subprocess.Popen(bashCommand, stdout=subprocess.PIPE, shell=True)
    output, error = process.communicate()

    bashCommand = "sudo ifconfig " + cp_intf + " up promisc"
    process = subprocess.Popen(bashCommand, stdout=subprocess.PIPE, shell=True)
    output, error = process.communicate()


def get_cp_intf_down(dp_intf, cp_intf):
    bashCommand = "sudo ip link delete " + dp_intf + " > /dev/null 2>&1 || true"
    process = subprocess.Popen(bashCommand, stdout=subprocess.PIPE, shell=True)
    output, error = process.communicate()

    bashCommand = "sudo ip link delete " + cp_intf + " > /dev/null 2>&1 || true"
    process = subprocess.Popen(bashCommand, stdout=subprocess.PIPE, shell=True)
    output, error = process.communicate()
```
