### ISSUE TITLE
ImportError: No module named bmpy_utils

### ISSUE THREAD

**Issue by xjywhu** [nsg-ethz/p4-utils#19]
I had installed bmv2, however when I run the exercise "11-Packet-Loss-Detection" with command "sudo python2 packet-loss-controller.py --option run", I met the following error:
Traceback (most recent call last):
  File "packet-loss-controller.py", line 2, in <module>
    from p4utils.utils.sswitch_API import *
  File "/home/ylj/xjy/p4/p4-utils/p4utils/utils/sswitch_API.py", line 25, in <module>
    import p4utils.utils.runtime_API as runtime_API
  File "/home/ylj/xjy/p4/p4-utils/p4utils/utils/runtime_API.py", line 31, in <module>
    import bmpy_utils as utils
ImportError: No module named bmpy_utils

**Comment by kartikx** [comment]
`bmpy_utils` is provided in the behvioural-model repo [here](https://github.com/p4lang/behavioral-model/blob/main/tools/bmpy_utils.py). If you haven't built the repo you should do that.
If the issue still persists, you can write
```
import sys
sys.path.append('/path-to-bmpy_utils-dir`)
```
at the start of packet-loss-controller.py to indicate to python the directory it should look in.

**Comment by xjywhu** [comment]
That works，thanks a lot!
