### ISSUE TITLE
ModuleNotFoundError: No module named 'p4utils.mininetlib.p4net'

### ISSUE THREAD

**Issue by ohnowade** [nsg-ethz/p4-utils#32]
Hi all,

My environment is Ubuntu 18.04 and my GCC version is 7.5. I have installed all the dependencies using the script provided and run install.sh. When I tired to start p4run, this error occurs.

Traceback (most recent call last):
  File "/usr/local/bin/p4run", line 11, in <module>
    load_entry_point('p4utils', 'console_scripts', 'p4run')()
  File "/home/ubuntu/p4-utils/p4utils/p4run.py", line 739, in main
    verbosity=args.verbosity)
  File "/home/ubuntu/p4-utils/p4utils/p4run.py", line 308, in __init__
    mininet = load_custom_object(mininet_module)
  File "/home/ubuntu/p4-utils/p4utils/utils/helper.py", line 321, in load_custom_object
    module = importlib.import_module(module_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'p4utils.mininetlib.p4net'

Does anyone know how to fix this? 

Thank you so much!

**Comment by edgar-costa** [comment]
Does `import p4utils` work?

**Comment by Benature** [comment]
Hi, I am using the preconfigured VM, encountered same problem
![image](https://user-images.githubusercontent.com/35028647/174267273-3cdb5a93-ef44-47e7-968e-3fd92810d504.png)
here import p4utils work, and python is version 3

**Comment by edgar-costa** [comment]
Which version of the VM are you using? Did you pull and got the latest p4utils? 

`p4net` is an older module that does not exist anymore. It seems that you might have the old `p4run` installed with the newer code or something like that. 

Try to `git pull` the repo and check if the problem disappears. Also you could try to install it again, see `install.sh`.

**Comment by edgar-costa** [comment]
I just tested with the provided VM, and the example at `p4utils/examples/switches` and it worked. 

```
p4@ict-networks-010-000-002-015:~/p4-tools/p4-utils/examples/switches$ sudo p4run --config p4app.json
```

**Comment by Benature** [comment]
Sorry, my `p4app.json` is too old, updated `p4app.json` works with `p4run`
