### ISSUE TITLE
Is the preconfigured p4-utils-vm only has a tty shell when start it?

### ISSUE THREAD

**Issue by whyLongWay** [nsg-ethz/p4-utils#50]
I use qemu-img to convert p4-utils-vm.qcow2 to VDI format (for virtual box), but when I start the vm, there is only a tty shell, no ubuntu desktop. I want to confirm it. Or maybe the convert is wrong somewhere.  Thanks.

Also, if I use qemu-system-**.exe to start this preconfigured vm, are there any  recommended commands parameters to start the preconfigured vm? Is there a command example? Thanks.

**Comment by elcobenoz** [comment]
its shell only, u need to install ubuntu desktop if u want a desktop. 
https://www.youtube.com/watch?v=98YuVDj6g8Q

**Comment by whyLongWay** [comment]
Thank you for your reply @elcobenoz
