### ISSUE TITLE
Installing issue

### ISSUE THREAD

**Issue by MohamadAlAdraa** [nsg-ethz/p4-utils#62]
Hi,

I am trying to install p4-utils on ubuntu 22.04. I am using the new install script. It is installed successfully. When I try to write a controller, I am importing the following module:
from p4utils.utils.sswitch_thrift_API import SimpleSwitchThriftAPI

which is giving me the following error:
Traceback (most recent call last):
  File "/home/mohamad/testbed-P4-emulator/controllers/ciena-controller.py", line 2, in <module>
    from p4utils.utils.sswitch_thrift_API import SimpleSwitchThriftAPI
  File "/home/mohamad/p4-tools/p4-utils/p4utils/utils/sswitch_thrift_API.py", line 34, in <module>
    from sswitch_runtime import SimpleSwitch
ModuleNotFoundError: No module named 'sswitch_runtime'

so inside the sswitch_thrift_API.py there is the following imports:
from sswitch_runtime import SimpleSwitch
from sswitch_runtime.ttypes import *

so sswitch_runtime cannot be found, what can be the problem?

thank you

**Comment by edgar-costa** [comment]
Does it work if you do `import p4utils`?

**Comment by MohamadAlAdraa** [comment]
Hi @edgar-costa,

Yes, see the following image.
![Capture](https://github.com/nsg-ethz/p4-utils/assets/96432152/f87ac6fa-7bc8-4f6a-9ca4-e986784c4661)

the only missing module is sswitch_runtime, as you see here it is not there compiler is not able to find this module.
![Capture1](https://github.com/nsg-ethz/p4-utils/assets/96432152/bb8489ad-10b6-44cb-8c6a-b0a9cc730e7a)

Is it something need to be fixes in the installation file? 

Thanks.

**Comment by edgar-costa** [comment]
Did you install `bmv2` and `p4c` with my scripts? Or only `p4utils`? I think that might be the problem.

**Comment by MohamadAlAdraa** [comment]
Hi @edgar-costa,

My last question would be, what is the difference between setQueueMaxSize and set_queu_depth and set_queue_rate?

**Comment by edgar-costa** [comment]
Hi @MohamadAlAdraa ,

Did what I told you to do in the last message fix the issue? I would like to know it. 

Answering your questions:

- `set_queue_depth` sets the number of packets a port queue can hold, so basically its size.
-  `set_queue_rate` sets the maximum rate packets will be emptied from the queue. If you set it at a lower rate than your input packet rate, when `queue_depth` packets are in the queue, they will start to be dropped.

**Comment by MohamadAlAdraa** [comment]
Hi @edgar-costa,

Yes, I was pulling the main from bmv2 and p4c and changing on them. However, when I pulled the exact commit you are specifying in the installation script and I changed on it, it worked fine.

Thank you for your help.
