### ISSUE TITLE
Username and password for pre-installed VM

### ISSUE THREAD

**Issue by yozzy-woo** [nsg-ethz/p4-utils#63]
Hi author, 
thank you for providing the pre-installed VM.
I have opened it, but it seems to use the username and password.
I can not find the relevant information in the documentation.
Can you help me, please?
![image](https://github.com/nsg-ethz/p4-utils/assets/77085377/6a23edab-d23e-4f57-a9fc-66fb3065ad89)

**Comment by edgar-costa** [comment]
Ah yes, somehow that information is not very clear. Username `p4`, password`p4`. Make sure you change your password after, just in case!

**Comment by yozzy-woo** [comment]
okay, thank you
